export enum FilterType {
  NEW = "NEW",
  TOP_TODAY = "TOP_TODAY",
  TOP_THIS_WEEK = "TOP_THIS_WEEK",
  TOP_THIS_MONTH = "TOP_THIS_MONTH",
  TOP_THIS_YEAR = "TOP_THIS_YEAR",
  TOP_ALL_TIME = "TOP_ALL_TIME"
}
