version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: redditclone_postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: reddit_clone_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: